services:
  backend:
    build: ./Backend
    ports:
      - 127.0.0.1:5000:5000
    # image: class-costs-backend
  frontend:
    build: ./Frontend
    ports: 
      - 127.0.0.1:3000:3000
    # image: class-costs-frontend